language: php
services:
  - mysql
before_script:
  - chmod 755 tools/travis_ci/before_script.sh
  - tools/travis_ci/before_script.sh
php:
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - hhvm
 - nightly
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  include:
    - php: hhvm
      dist: trusty
