/*
selectivizr v1.0.3b - (c) Keith Clark, freely distributable under the terms
of the MIT license.

selectivizr.com
*/
 (function(m){function D(a){return a.replace(E,"$1").replace(F,function(a,d,c){a=c.split(",");c=0;for(var e=a.length;c<e;c++){var h=G(a[c].replace(H,"$1").replace(I,"$1"))+" ",g=[];a[c]=h.replace(J,function(a,b,c,d,e){return b?(0<g.length&&(r.push({selector:h.substring(0,e),patches:g}),g=[]),b):(b=c?K(c):!w||w.test(d)?{className:x(d),applyClass:!0}:null)?(g.push(b),"."+b.className):a})}return d+a.join(",")})}function K(a){var b=!0,d=x(a.slice(1)),c=":not("==a.substring(0,5),e,h;c&&(a=a.slice(5,-1));
 var g=a.indexOf("(");-1<g&&(a=a.substring(0,g));if(":"==a.charAt(0))switch(a.slice(1)){case "root":b=function(a){return c?a!=t:a==t};break;case "target":if(8==n){b=function(a){var b=function(){var b=location.hash,d=b.slice(1);return c?""==b||a.id!=d:""!=b&&a.id==d};k(m,"hashchange",function(){l(a,d,b())});return b()};break}return!1;case "checked":b=function(a){L.test(a.type)&&k(a,"propertychange",function(){"checked"==event.propertyName&&l(a,d,a.checked!==c)});return a.checked!==c};break;case "disabled":c=
 !c;case "enabled":b=function(b){return M.test(b.tagName)?(k(b,"propertychange",function(){"$disabled"==event.propertyName&&l(b,d,b.$disabled===c)}),u.push(b),b.$disabled=b.disabled,b.disabled===c):":enabled"==a?c:!c};break;case "focus":e="focus",h="blur";case "hover":e||(e="mouseenter",h="mouseleave");b=function(a){k(a,c?h:e,function(){l(a,d,!0)});k(a,c?e:h,function(){l(a,d,!1)});return c};break;default:if(!N.test(a))return!1}return{className:d,applyClass:b}}function O(){for(var a,b,d,c,e=0;e<r.length;e++){b=
 r[e].selector;d=r[e].patches;c=b.replace(P,"");if(""==c||" "==c.charAt(c.length-1))c+="*";try{a=y(c)}catch(h){m.console&&m.console.log("Selector '"+b+"' threw exception '"+h+"'")}if(a)for(b=0,c=a.length;b<c;b++){for(var g=a[b],f=g.className,k=0,n=d.length;k<n;k++){var l=d[k];(new RegExp("(^|\\s)"+l.className+"(\\s|$)")).test(g.className)||!l.applyClass||!0!==l.applyClass&&!0!==l.applyClass(g)||(f=z(f,l.className,!0))}g.className=f}}}function x(a){return"slvzr-"+(6==n?Q++:a.replace(R,function(a){return a.charCodeAt(0)}))}
 function G(a){return a.replace(A,"$1").replace(S," ")}function l(a,b,d){var c=a.className;b=z(c,b,d);b!=c&&(a.className=b,a.parentNode.className+="")}function z(a,b,d){var c=RegExp("(^|\\s)"+b+"(\\s|$)"),e=c.test(a);return d?e?a:a+" "+b:e?a.replace(c,"$1").replace(A,"$1"):a}function k(a,b,d){a.attachEvent("on"+b,d)}function v(a,b,d){b||(b=T);"//"==a.substring(0,2)&&(a=b.substring(0,b.indexOf("//"))+a);if(/^https?:\/\//i.test(a))return d||b.substring(0,b.indexOf("/",8))==a.substring(0,a.indexOf("/",
 8))?a:null;if("/"==a.charAt(0))return b.substring(0,b.indexOf("/",8))+a;b=b.split(/[?#]/)[0];"?"!=a.charAt(0)&&"/"!=b.charAt(b.length-1)&&(b=b.substring(0,b.lastIndexOf("/")+1));return b+a}function B(a){return a?(p.open("GET",a,!1),p.send(),(200==p.status?p.responseText:"").replace(U,"").replace(V,function(b,d,c,e,f,g){b=B(v(c||f,a));return g?"@media "+g+" {"+b+"}":b}).replace(W,function(b,d,c,e){c=c||"";return d?b:" url("+c+v(e,a,!0)+c+") "})):""}function X(){for(var a,b,d=0;d<f.styleSheets.length;d++)if(b=
 f.styleSheets[d],""!=b.href&&(a=v(b.href)))b.cssText=b.rawCssText=D(B(a))}function Y(){O();0<u.length&&setInterval(function(){for(var a=0,b=u.length;a<b;a++){var d=u[a];d.disabled!==d.$disabled&&(d.disabled?(d.disabled=!1,d.$disabled=!0,d.disabled=!0):d.$disabled=d.disabled)}},250)}function Z(a,b){var d=!1,c=!0,e=function(c){if("readystatechange"!=c.type||"complete"==f.readyState)("load"==c.type?a:f).detachEvent("on"+c.type,e,!1),!d&&(d=!0)&&b.call(a,c.type||c)},h=function(){try{t.doScroll("left")}catch(a){setTimeout(h,
 50);return}e("poll")};if("complete"==f.readyState)b.call(a,"");else{if(f.createEventObject&&t.doScroll){try{c=!a.frameElement}catch(g){}c&&h()}k(f,"readystatechange",e);k(a,"load",e)}}var q=navigator.userAgent.match(/MSIE (\d+)/);if(!q)return!1;var f=document,t=f.documentElement,p=function(){if(m.XMLHttpRequest)return new XMLHttpRequest;try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(a){return null}}(),n=q[1];if(!("CSS1Compat"!=f.compatMode||6>n||8<n)&&p){var C={NW:"*.Dom.select",MooTools:"$$",
 DOMAssistant:"*.$",Prototype:"$$",YAHOO:"*.util.Selector.query",Sizzle:"*",jQuery:"*",dojo:"*.query"},y,u=[],r=[],Q=0,U=/(\/\*[^*]*\*+([^\/][^*]*\*+)*\/)\s*?/g,V=/@import\s*(?:(?:(?:url\(\s*(['"]?)(.*)\1)\s*\))|(?:(['"])(.*)\3))\s*([^;]*);/g,W=/(behavior\s*?:\s*)?\burl\(\s*(["']?)(?!data:)([^"')]+)\2\s*\)/g,N=/^:(empty|(first|last|only|nth(-last)?)-(child|of-type))$/,E=/:(:first-(?:line|letter))/g,F=/((?:^|(?:\s*})+)(?:\s*@media[^{]+{)?)\s*([^\{]*?[\[:][^{]+)/g,J=/([ +~>])|(:[a-z-]+(?:\(.*?\)+)?)|(\[.*?\])/g,
 P=/(:not\()?:(hover|enabled|disabled|focus|checked|target|active|visited|first-line|first-letter)\)?/g,R=/[^\w-]/g,M=/^(INPUT|SELECT|TEXTAREA|BUTTON)$/,L=/^(checkbox|radio)$/,w=6<n?/[\$\^*]=(['"])\1/:null,H=/([(\[+~])\s+/g,I=/\s+([)\]+~])/g,S=/\s+/g,A=/^\s*((?:[\S\s]*\S)?)\s*$/,q=f.getElementsByTagName("BASE"),T=0<q.length?q[0].href:f.location.href;X();Z(m,function(){for(var a in C){var b,d,c=m;if(m[a]){for(b=C[a].replace("*",a).split(".");(d=b.shift())&&(c=c[d]););if("function"==typeof c){y=c;Y();
 break}}}})}})(this);