title: Hero Banner
context:
  hero-banner:
    img: http://placehold.it/3000x1200/48b183/ffffff?text=c3000x900-ct~30
    heading: It's a lovely heading
    description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
  button:
    text: Hero banner cta


