title: "Button component"
collated: true
context:
  #modifier:
  button:
    text: "Read more"
variants:
  -
    name: small
    context:
      modifier: button--small
      button:
        text: "small button"
  -
    name: large
    context:
      modifier: button--large
      button:
        text: "large button"
  -
    name: alt
    context:
      modifier: button--alt
      button:
        text: "alt button"
  -
    name: neutral
    context:
      modifier: button--neutral
      button:
        text: "neutral button"
  -
    name: Warning
    context:
      modifier: button--warning
      button:
        text: "warning button"
  -
    name: positive
    context:
      modifier: button--positive
      button:
        text: "positive button"
  -
    name: block
    context:
      modifier: button--block
      button:
        text: "block button"
  -
    name: disabled
    context:
      modifier: button--disabled
      button:
        text: "disabled button"
