title: "Button component"
collated: true
context:
 modifier: default
 button:
  text: "Read more"
variants:
 -
  name: small
  context:
   modifier: small
   button:
    text: "small button"
 -
  name: large
  context:
   modifier: large
   button:
    text: "large button"
 -
  name: alt
  context:
   modifier: alt
   button:
    text: "alt button"
 -
  name: neutral
  context:
   modifier: neutral
   button:
    text: "neutral button"
 -
  name: Warning
  context:
   modifier: warning
   button:
    text: "warning button"
 -
  name: positive
  context:
   modifier: positive
   button:
    text: "positive button"
 -
  name: block
  context:
   modifier: block
   button:
    text: "block button"
 -
  name: disabled
  context:
   modifier: disabled
   button:
    text: "disabled button"