status: WIP
notes: There is different HTML when a client doesn't upload a thumbnail. Could you add that 2 one of the list items?
context:
  children-pg-list-item:
    img: http://placehold.it/400x300
    text: this is a title that is really rather long