title: Top Heavy list
notes: A list of tiles which handles weird low numbers of items by making the first row large without much effort other than specific classes. Requires a wrapper class like <code>container</code> to not force a horizontal scroll.
status: wip
preview: "@preview-grey"
context:
  modifier: top-heavy-list--one
  tile-list:
    tiles:
    -
      tile:
        img: http://placehold.it/300x200
        heading: Top heavy list with 1 item
        text: Top Heavy list
      button:
        text: Read more
variants:
  -
    name: 'top-heavy-list--two'
    context:
      modifier: top-heavy-list--two
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--three'
    context:
      modifier: top-heavy-list--three
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--four'
    context:
      modifier: top-heavy-list--four
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--five'
    context:
      modifier: top-heavy-list--five
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--six'
    context:
      modifier: top-heavy-list--six
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--seven'
    context:
      modifier: top-heavy-list--seven
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--even'
    context:
      modifier: top-heavy-list--even
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
  -
    name: 'top-heavy-list--odd'
    context:
      modifier: top-heavy-list--odd
      tile-list:
        tiles:
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: Top Heavy list
          button:
            text: Read more
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
        -
          tile:
            img: http://placehold.it/300x200
            heading: A lovely heading
            text: More ipsum
          button:
            text: Sign up
