status: ready
title: Breadcrumb
notes: A breadcrumb keeps track of the hierarchical structure of content, and where the current page you're on fits in. It lists the given page's parent pages and then the homepage.
context:
  breadcrumb:
      currentpage: current page
      breadcrumbList:
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: home
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: another page
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: a third page
