status: wip
title: Breadcrumb
notes: Let's grab my fancy mobile show/hide stuff from Tango. These are so often problematic on mobile.
context:
  breadcrumb:
      currentpage: current page
      breadcrumbList:
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: home
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: another page
      -
        breadcrumbItem:
          link: https://www.lifewire.com/html5-placeholder-links-3468070
          text: a third page
