title: "Button component"
collated: true
status: wip
notes: Warning button needs CSS 
context:
  button:
    modifier: " "
    text: "Read more"
variants:
  -
    name: small
    context:
      button:
        modifier: button--small
        text: "small button"
  -
    name: large
    context:
      button:
        modifier: button--large
        text: "large button"
  -
    name: alt
    context:
      button:
        modifier: button--alt
        text: "alt button"
  -
    name: neutral
    context:
      button:
        modifier: button--neutral
        text: "neutral button"
  -
    name: Warning
    context:
      button:
        modifier: button--warning
        text: "warning button"
  -
    name: positive
    context:
      button:
        modifier: button--positive
        text: "positive button"
  -
    name: block
    context:
      button:
        modifier: button--block
        text: "block button"
  -
    name: disabled
    context:
      button:
        modifier: button--disabled
        text: "disabled button"
