title: "Text links"
collated: true
context:
  text-link:
    modifier: " "
    text: "Read more"
variants:
  -
   name: "right arrow after"
   context:
    text-link:
      modifier: "-r-arrow-after"
      text: "right arrow after"
  -
   name: "right arrow before"
   context:
    text-link:
      modifier: "-r-arrow-before"
      text: "right arrow before"
  -
   name: "left arrow after"
   context:
    text-link:
      modifier: "-l-arrow-after"
      text: "left arrow after"
  -
   name: "left arrow before"
   context:
    text-link:
      modifier: "-l-arrow-before"
      text: "left arrow before"