title: Article
notes: A feature article with image. Requires a wrapper class like <code>container</code> to not force a horizontal scroll.
context:
  article:
    img: http://placehold.it/400x300
    heading: A lovely long and generous heading about a specific thing
    date: 23 September 2018
    author: Hailey Summers
    text: Nulla facilisi. Integer finibus purus eros, quis sodales diam pulvinar quis. Pellentesque non quam quis urna viverra mattis. Nulla facilisi. Sed id consectetur neque, nec euismod magna. Vestibulum orci sem, suscipit tempor tempus nec, rhoncus vitae diam. Vestibulum pellentesque id neque et pretium.




