title: Home
status: wip
context:
  site-name: Sprout 3 Component Library
  tile-list: '@tile-list.tile-list'
  block-list: '@block-list.block-list'
  hero-banner:
    img: http://placehold.it/2048x780/48b183/ffffff?text=c2048x780-ct~35
    heading: Very basic Hero Banner
    description: This banner is pretty simple which means less troubles, but also servers the same image for every resolution which makes it not so great for mobile.
  button:
    text: 'Hero banner cta'



