#!/usr/bin/env bash
set -e

run() {
  [ -x $1 ] && $1 || exit $?
}

umask 002

git submodule sync && git submodule update --init --recursive

run deploy/before_restart
run deploy/restart && run deploy/after_restart

echo "Done."
