title: Events list
notes: A list of upcoming events
preview: "@preview-modules"
context:
  event-list:
    events:
    -
      event:
        title: A lovely heading
        img: http://placehold.it/600x600
        img-alt: This is ap placeholder image
        date: 08-08-2019
        day: 8
        month: Aug
        year: 2019
        event-link: https://www.karmabunny.com.au/
        description: Veniam aut or culpa irure or accusantium but consectetur yet aliqua. Eum do yet labore...
        location: 95 Beulah Road, Norwood
        external-link: https://www.karmabunny.com.au/what_we_do/web_design
    -
      event:
        title: Esse nequeporro eiusmod numquam fugiat
        img: http://placehold.it/600x600
        img-alt: This is ap placeholder image
        date: 31-09-2019
        day: 31
        month: Sept
        year: 2019
        event-link: https://www.karmabunny.com.au/
        description: Est corporis but aliquip, si dicta for odit aliquip...
        location: 95 Beulah Road, Norwood
        external-link: https://www.karmabunny.com.au/what_we_do/web_design
    -
      event:
        title: A longer heading for fun
        img: http://placehold.it/600x600
        img-alt: This is ap placeholder image
        date: 02-10-2019
        day: 2
        month: Oct
        year: 2019
        event-link: https://www.karmabunny.com.au/
        description: Officia eaque or eiusmod or mollit nor esse so eius. Minim id and quisquam nor proident perspiciatis. Voluptas quo perspiciatis or cillum but elit for dicta aperiam...
        location: 95 Beulah Road, Norwood
        external-link: https://www.karmabunny.com.au/what_we_do/web_design