title: Hero Banner
context:
  hero-banner:
    img: http://placehold.it/960x660/48b183/ffffff?text=c960x660-ct~30
    img-lgmob: http://placehold.it/1536x1056/48b183/ffffff?text=c1536x1056-ct~35
    img-tb-portrait: http://placehold.it/1984x1364/48b183/ffffff?text=c1984x1364-ct~35
    img-tb-landscape: http://placehold.it/2425x1364/48b183/ffffff?text=c2400x1364-ct~35
    img-desk-sm: http://placehold.it/3100x1364/48b183/ffffff?text=c3100x1364-ct~35
    img-desk-lg: http://placehold.it/3100x1364/48b183/ffffff?text=c3100x1364-ct~35
    heading: It's a lovely heading
    description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.

  tile-list: '@tile-list.tile-list'

