#!/usr/bin/env bash
#
# Git deploy hooks.
# Karmabunny 2020
#

TARGET="deploy-hooks/run.sh"

# Read in the received branch info.
if ! read oldrev newrev ref; then
    echo "DH: Missing stdin."
    exit 1
fi

# If you've got an arcane git path.
# Typically it's just parent, but to be sure.
while ! [[ -d "$(dirname $TARGET)" ]]; do
    cd ..
    if [[ "$(pwd)" == "/" ]]; then
        echo "DH: Could not find '$TARGET'."
        exit 1
    fi
done

BRANCH="$(git rev-parse --abbrev-ref $ref)"

# Some stats.
echo "DH: $(pwd)"
echo "DH: $BRANCH"
echo "DH: $(git --version)"

# Enable this if the git version is < 2.3
# git reset HEAD --hard

# Hook into our hooks script. lol.
echo "DH: Found '$TARGET'."
./$TARGET $BRANCH && exit $?
